# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linearselectionC <- function(w, z) {
    .Call(`_phenoselection_linearselectionC`, w, z)
}

linearresponseC <- function(B, g) {
    .Call(`_phenoselection_linearresponseC`, B, g)
}

quadraticselectionC <- function(w, z) {
    .Call(`_phenoselection_quadraticselectionC`, w, z)
}

quadraticresponseC <- function(P, g, gamma, s, B) {
    .Call(`_phenoselection_quadraticresponseC`, P, g, gamma, s, B)
}

PHENOSELECTIONc <- function(w, z, g, replicates) {
    .Call(`_phenoselection_PHENOSELECTIONc`, w, z, g, replicates)
}

PHENOSELECTIONcboot <- function(w, z, g, r, debug) {
    .Call(`_phenoselection_PHENOSELECTIONcboot`, w, z, g, r, debug)
}

rcpparma_hello_world <- function() {
    .Call(`_phenoselection_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_phenoselection_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_phenoselection_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_phenoselection_rcpparma_bothproducts`, x)
}

